client/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('clients.urls')),
]

clients/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.main, name='main'),
    path('login/', auth_views.LoginView.as_view(template_name='clients/loginpage.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('<int:user_id>/storage/', views.user_storage, name='storage'),
    
    path('recommendation/', views.recommendation, name='recommendation'),
    path('review/', views.review, name='review'),
    path('for_review/', views.for_review, name = 'for_review'),
    path('get_review/<str:lecture_title>', views.get_review, name = 'get_review'),
]

clients/models.py
from djongo import models

class Recommendation(models.Model):
    lecture_id = models.CharField(max_length=20)
    lecture_name = models.CharField(max_length=100)

    class Meta:
        abstract = True

class CategoryLog(models.Model):
    _id = models.ObjectIdField()
    user_id = models.IntegerField(blank=True)
    add_date = models.DateTimeField(auto_now_add=True)
    
    grade = models.CharField(max_length=20)
    subject = models.CharField(max_length=20)
    achivement = models.CharField(max_length=20)
    site = models.CharField(max_length=20)
    tag_jobdam = models.CharField(max_length=20)
    tag_pilgi = models.CharField(max_length=20)
    tag_jindo = models.CharField(max_length=20)

    objects = models.DjongoManager()

class Lecture(models.Model) :
    title = models.CharField(max_length=100)
    teacher = models.CharField(max_length=100)
    subject = models.CharField(max_length=100)
    grade = models.CharField(max_length=100)
    link = models.CharField(max_length=200)

class ReviewLog(models.Model):
    _id = models.ObjectIdField()
    user_id = models.IntegerField(blank=True)
    lecture_id = models.CharField(blank=True, max_length=30)
    lecture_title = models.CharField(blank=True, max_length=30)
    add_date = models.DateTimeField(auto_now_add=True)
    achivement = models.CharField(max_length=20)
    tag_jobdam = models.CharField(max_length=20)
    tag_pilgi = models.CharField(max_length=20)
    tag_jindo = models.CharField(max_length=20)
    lec_comment = models.CharField(max_length = 1000)

    objects = models.DjongoManager()

clients/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import fields
from .models import CategoryLog, ReviewLog


class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

class CategoryLogForm(forms.ModelForm):
    class Meta:
        model = CategoryLog
        fields = '__all__'

class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewLog
        fields = '__all__'

clients/views.py
from django.http import request
from django.shortcuts import render, redirect
from django.contrib import messages 
from django.contrib.auth import authenticate, login
from clients.forms import ReviewForm
from clients.models import CategoryLog,ReviewLog
from clients.forms import UserForm, CategoryLogForm, ReviewForm
from pymongo import MongoClient

from django.views.decorators.csrf import csrf_exempt
from django.core.paginator import Paginator

import os, json
from bson.objectid import ObjectId
from pathlib import Path

#mongoDB서버 연동
def connect_lecture_db():
    mongodb_uri = "mongodb+srv://mycl:{}@lecture.ks2gr.mongodb.net/mycl?retryWrites=true&w=majority".format(os.environ.get('MONGO_PW'))
    myclient = MongoClient(mongodb_uri)
    mydb = myclient.get_database("lecture")
    return mydb

#_id값 찾기 -> connect_lecture_db()와 연결 되어있음
#title 제목으로 searching 시 _id값 하나 반환
def searching_id(key_name, value_name, site_name):
    lecture_id_list = []
    mycol = connect_lecture_db().get_collection(site_name)
    for di in mycol.find({}, {key_name: 1}):
        if di.get(key_name) == value_name:
            if key_name == "title":
                lecture_id = di.get("_id")
                return lecture_id
            else:
                lecture_id_list.append(di.get("_id"))

    return lecture_id_list


#과목, 학년으로 뽑아낸 list 교집합 ->lecture_id_list
#list2개 교집합 list형태로 반환
def list_intersection(list1, list2):
    li = list(set(list1).intersection(list2))
    return li

#_id와 tag_data값으로 dict만들기
def data_make_dict(lecture_id_list, tag_name, tag_data):
    id_list = []
    tag_value = []
    mycol = connect_lecture_db().get_collection(tag_name)
    for di in mycol.find({}, {tag_data: 1}):
        for i in range(len(lecture_id_list)):
            if di.get("_id") == lecture_id_list[i]:
                id_list.append(di.get("_id"))
                tag_value.append(di.get(tag_data))
    dic = dict(zip(id_list, tag_value))
    return dic

#dict에서 특정한 수의 max값 추출 하여 list로 반환
def max_filtering(dic_length, dic):
    max_id_data = []
    cnt = 0
    while(cnt < dic_length*9/10):
        if dic_length <= 5:
            return list(dic.keys())                     #5개 이하면 그대로 key값만 반환
        else:
            max_data = max(dic, key=dic.get)
            max_id_data.append(max_data)
            del dic[max_data]
            cnt += 1

    return max_id_data

#리뷰데이터 코멘트 로딩
def review_comment_load(idv):
    key = ReviewLog.objects.all()
    for k in key:
        if key.lecture_id == idv:
            return key.lec_comment
        else:
            pass

#결과값 title을 list로 반환
def recommendation_res_title(res_list, tag_name):
    rec_res_list = []
    mycol = connect_lecture_db().get_collection(tag_name)

    for i in res_list:
        for di in mycol.find():
            if di.get("_id") == i:
                di.pop("_id")
                temp = list(di.values())
                # temp.append(review_comment_load(i))         #comment부분 추가
                rec_res_list.append(temp)
    return rec_res_list

#tag 값 update
def update_tag_data(lecture_id, tag_name, tag_data):
    
    mycol = connect_lecture_db().get_collection(tag_name)
    for di in mycol.find({}, {tag_data: 1}):
        temp = di.get(tag_data) + 1

        if di.get("_id") == ObjectId(lecture_id):  # lecture에서 찾은 id값과 tag_ ***의 id값 일치 --> 태그값 +1 후에 수정
            mycol.update_one({"_id": ObjectId(lecture_id)}, {"$set": {tag_data: temp}})

            

#가장 최신 리뷰 데이터 update
def reviewlog_load():
    key = ReviewLog.objects.last()
    update_tag_data(key.lecture_id, "tag_achivement", key.achivement)
    update_tag_data(key.lecture_id, "tag_jobdam", key.tag_jobdam)
    update_tag_data(key.lecture_id, "tag_pilgi", key.tag_pilgi)
    update_tag_data(key.lecture_id, "tag_jindo", key.tag_jindo)

#사용자가 선택한 tag_data 딕셔너리
def choice_tag_dict(key):
    tag_dict = {"jobdam": key.tag_jobdam,
                "jindo": key.tag_jindo,
                "pilgi": key.tag_pilgi,
                "site": key.site,
                "achivement": key.achivement
                }
    return tag_dict
################################################################################

def main(request):
    if request.method == "POST":
        form  = CategoryLogForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)  
            form.user_id = request.user.id
            form.save()
            return redirect('recommendation')
        
        else:
            messages.error(request, "모든 카테고리를 선택해주세요.")
    return render(request, 'clients/landingpage.html')

@csrf_exempt
def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('main')
    else:
        form = UserForm()
    return render(request, 'clients/registerpage.html', {'form': form})

def user_storage(request, user_id):
    user_db = connect_lecture_db().get_collection("auth_user")
    category_log = connect_lecture_db().get_collection("clients_categorylog")
    review_log = connect_lecture_db().get_collection("clients_reviewlog")

    user = user_db.find_one({"id": user_id})
    category = category_log.find({"user_id": user_id})
    review = review_log.find({"user_id": user_id})

    return render(request, 'clients/mystoragepage.html', {'user': user, 'category': category, 'review': review})
    
def recommendation(request):
    key = CategoryLog.objects.last()

    #문자열 부분 사이트에서 데이터 받아와야 함
    lecture_id_list1 = searching_id("subject", key.subject, "data_{}".format(key.site))
    lecture_id_list2 = searching_id("grade", key.grade, "data_{}".format(key.site))
    intersection_id_list = list_intersection(lecture_id_list1, lecture_id_list2)

    dic = data_make_dict(intersection_id_list, "tag_jindo", key.tag_jindo)
    dic2 = data_make_dict(max_filtering(len(dic),dic), "tag_jobdam", key.tag_jobdam)
    dic3 = data_make_dict(max_filtering(len(dic2),dic2), "tag_pilgi", key.tag_pilgi)
    dic4 = data_make_dict(max_filtering(len(dic3),dic3), "tag_achivement", key.achivement)

    reslist = max_filtering(len(dic4), dic4)
    rec_res_list = recommendation_res_title(reslist, "data_{}".format(key.site))
    cho_tag = choice_tag_dict(key)

    # x 눌렀을 시 2개씩 계속 출력
    paginator = Paginator(rec_res_list, 2)
    page = request.GET.get('page')
    posts = paginator.get_page(page)

    # recommendation log 추가
    rec_log_db = connect_lecture_db().get_collection("clients_recommendationlog")
    log = {'user_id': key.user_id, 'lec_list': rec_res_list}
    rec_log_db.insert(log)

    return render(request, 'clients/recommendationpage.html', {"list": rec_res_list, 'posts': posts, 'cho_tag' : cho_tag})


@csrf_exempt
def review(request):
    ebsi = connect_lecture_db().get_collection("data_ebsi")
    mega = connect_lecture_db().get_collection("data_megastudy")
    etoos = connect_lecture_db().get_collection("data_etoos")
    site_text = request.POST.get('site')
    search_key = request.POST.get('search_key')
    post_lec = {}
    if(site_text=="ebsi") :
        if search_key :
            post_lec = ebsi.find({"$or" : [{'title':{'$regex':search_key}} , {'title':search_key}]})
            return render(request, 'clients/reviewpage.html', {'post_lec' : post_lec})
    elif(site_text=="mega") :
        if search_key :
            post_lec = mega.find({"$or" : [{'title':{'$regex':search_key}} , {'title':search_key}]})
            return render(request, 'clients/reviewpage.html', {'post_lec' : post_lec})
    elif(site_text=="etoos") :
        if search_key :
            post_lec = etoos.find({"$or" : [{'title':{'$regex':search_key}} , {'title':search_key}]})
            return render(request, 'clients/reviewpage.html', {'post_lec' : post_lec})            
    
    return render(request, 'clients/reviewpage.html', {'post_lec' : post_lec})


@csrf_exempt
def for_review(request):
    ebsi = connect_lecture_db().get_collection("data_ebsi")
    mega = connect_lecture_db().get_collection("data_megastudy")
    etoos = connect_lecture_db().get_collection("data_etoos")

    lecture_title = request.GET.get('lecture_select')

    EBS = ebsi.find()
    MEGA = mega.find()
    ETO = etoos.find()

    lecture = {}

    for lec in EBS :
        if(lec.get("title") == lecture_title):
            lecture = lec
    for lec in MEGA :
        if(lec.get("title") == lecture_title):
            lecture = lec
    for lec in ETO :
        if(lec.get("title") == lecture_title):
            lecture = lec



    return render(request, 'clients/for_reviewpage.html', {'lecture' : lecture})


def get_review(request, lecture_title):
    
    if request.method == "POST":
        review_form  = ReviewForm(request.POST)
        if review_form.is_valid():
            review_form = review_form.save(commit=False)  
            review_form.user_id = request.user.id
            

            review_form.lecture_title = lecture_title
            for site in ['ebsi', 'megastudy', 'etoos']:
                if searching_id("title", lecture_title, "data_{}".format(site)):
                    review_form.lecture_id = searching_id("title", lecture_title, "data_{}".format(site))
                    break

            review_form.save()
            messages.info(request, "후기 등록이 완료되었습니다.")
            reviewlog_load()
            return redirect('main')
        
        else:
            messages.error(request, "모든 카테고리를 선택해주세요.")


    return render(request, 'clients/for_reviewpage.html')

clients/templates/clients/for_reviewpage.html
{% load static%}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/for_reviewpage.css' %}">
</head>

<body>
    <div id="page1">
        <div id="header">
            <a href="{% url 'main' %}"><img id="logo" alt="My.Cl 로고" src="{% static 'img/로고.jpg' %}" /></a>
            <div id="reviewheader">후기작성</div>
            <div id="auth" style="text-align: end;">
                {% if user.is_authenticated %}
                <a href="{% url 'logout' %}"><input type="button" id="authbutton" value="로그아웃"></a>
                <a href="{% url 'storage' user_id=user.id %}"><input type="button" id="authbutton"
                        value="{{ user.username }}님 마이페이지"></a>
                {% else %}
                <a href="{% url 'login' %}"><input type="button" id="authbutton" value="로그인"></a>
                <a href="{% url 'signup' %}"><input type="button" id="authbutton" value="회원가입"></a>
                {% endif %}
            </div>

            <hr size="5px" color="pink">


            <div id="lec_title">
                <a href="{{ lecture.link }}">{{ lecture.title }} 후기 작성하기</a>
            </div>
            
            <form action="{% url 'get_review' lecture_title=lecture.title %}" method='POST'> {% csrf_token %}
                <table style="width: 100%; margin-top : 0px; margin-left:auto; margin-right: auto;">
                    <tr style="vertical-align: top">
                        <td style="width:50%; border-right:5px solid #fdb0b0; text-align: center;">


                            <class id="components">
                                <div style="margin-top:30px; margin-bottom: 5px; font-size: 25px; font-weight: bolder;">등급
                                </div>
                                <div id="achievementbutton" style="justify-content: center; display: inline-block;">
                                    <input type="radio" id="abutton1" name="achivement" value="onetotwo" /><label for="abutton1"
                                        style="margin-right: 30px;">1-2등급</label>
                                    <input type="radio" id="abutton2" name="achivement" value="threetofour" /><label for="abutton2"
                                        style="margin-right: 30px;">3-4등급</label>
                                    <input type="radio" id="abutton3" name="achivement" value="fivetosix" /><label for="abutton3"
                                        style="margin-right: 30px;">5-6등급</label>
                                    <input type="radio" id="abutton4" name="achivement" value="seventonine" /><label
                                        for="abutton4">7-9등급</label>
                                </div>
                            </class>

                            <class id="components">
                                <div style="margin-top : 10px; margin-bottom: 5px; font-size: 25px; font-weight: bolder;">
                                    잡담양
                                </div>
                                <div id="chatbutton" style="justify-content: center; display: inline-block;">
                                    <input type="radio" id="cbutton1" name="tag_jobdam" value="low" /><label for="cbutton1"
                                        style="margin-right: 30px;">없음</label>
                                    <input type="radio" id="cbutton2" name="tag_jobdam" value="medium" /><label
                                        for="cbutton2" style="margin-right: 30px;">적당히</label>
                                    <input type="radio" id="cbutton3" name="tag_jobdam" value="high" /><label
                                        for="cbutton3">많음</label>
                                </div>
                            </class>
    
                            <class id="components">
                                <div style="margin-top:30px; margin-bottom: 5px; font-size: 25px; font-weight: bolder;">필기양
                                </div>
                                <div id="notebutton" style="justify-content: center; display: inline-block;">
                                    <input type="radio" id="nbutton1" name="tag_pilgi" value="low" /><label for="nbutton1"
                                        style="margin-right: 20px; ">없음</label>
                                    <input type="radio" id="nbutton2" name="tag_pilgi" value="medium" /><label
                                        for="nbutton2" style="margin-right: 20px; ">적당히</label>
                                    <input type="radio" id="nbutton3" name="tag_pilgi" value="high" /><label
                                        for="nbutton3">많음</label>
                                </div>
                            </class>
    
                            <class id="components">
                                <div style="margin-top:30px; margin-bottom: 5px; font-size: 25px; font-weight: bolder;">진도
                                </div>
                                <div id="progressbutton" style="justify-content: center; display: inline-block;">
                                    <input type="radio" id="probutton1" name="tag_jindo" value="low" /><label
                                        for="probutton1" style="margin-right: 30px;">천천히</label>
                                    <input type="radio" id="probutton2" name="tag_jindo" value="medium" /><label
                                        for="probutton2" style="margin-right: 30px;">적당히</label>
                                    <input type="radio" id="probutton3" name="tag_jindo" value="high" /><label
                                        for="probutton3">빠름</label>
                                </div>
                            </class>


                        </td>
                        <td style="width:50%; text-align: center;">

                            <div id="review_post">

                                <textarea name="lec_comment" value="{{ lec_comment }}" id="lec_comment"
                                    placeholder="강의에 대한 후기를 작성해주세요! (1000자 이내)"></textarea>
                            </div>

                        </td>
                    </tr>
                </table>


                <input id="submitbutton" class="submitbutton" type="submit" value="후기 등록하기">
            </form>
        </div>
</body>

clients/templates/clients/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert">
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert">
            {{ error }}
        </div>
    {% endfor %}
{% endif %}

clients/templates/clients/loginpage.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/loginpage.css' %}">
</head>

<body> 
    <div id="page1">
        <form action="{% url 'login' %}" method="post" class="loginForm">
            {% csrf_token %}
            {% include "clients/form_errors.html" %}
            <a href="{% url 'main' %}"><img id="logo" alt="My.Cl 로고" src="{% static 'img/로고.jpg' %}"/></a>
            <div id="logintext">로그인</div>
            <div class="idForm">
                <input type="text" class="id" name="username" id="username" placeholder="ID"
                    value="{{ form.username.value|default_if_none:'' }}">
            </div>
            <div class="passForm">
                <input type="password" class="pw" name="password" id="password" placeholder="PW"
                    value="{{ form.password.value|default_if_none:'' }}">
            </div>
            <button type="submit" class="btn">
                로그인
            </button>
            <div class="bottomText">
                아이디가 없으신가요? <a href="{% url 'signup' %}">회원가입</a>
            </div>
        </form>
    </div>

</body>

clients/templates/clients/mystoragepage.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/mystoragepage.css' %}">
</head>

<body>
    <div id="page1">
        <div id="header">
            <a href="{% url 'main' %}"><img id="logo" alt="My.Cl 로고" src="{% static 'img/로고.jpg' %}" /></a>
            <div id="stoheader">{{user.username}}님 마이페이지</div>
            <div id="auth" style="text-align: end;">
                <a href="{% url 'logout' %}"><input type="button" id="authbutton" value="로그아웃"></a>
            </div>

        </div>
        <hr size="5px" color="pink">

        <table style="width: 100%; margin-top : 0px; margin-left:auto; margin-right: auto;">
            <tr style="vertical-align: top">
                <td style="width:50%; border-right:5px solid #fdb0b0; text-align: center;">
                    {% for cat in category %}
                    <div id="box_model"
                        style="justify-content: center; display: inline-block; margin-bottom: 20px; margin: top 20px;">
                        <div id="rec_result">
                            <span id="date">{{cat.add_date}}에 선택한 카테고리</span>
                            
                            <table>
                                <p>
                                <td id = "cat_info"><span>학년 : {{cat.grade}} </span></td>
                                <td id = "cat_info"><span>과목 : {{cat.subject}} </span></td>
                                <td id = "cat_info"><span>등급 : {{cat.achivement}} </span></td>
                                <td id = "cat_info"><span>강의 사이트 : {{cat.site}}</span></td>
                                </p>
                            </table>
                            

                            <p id="tag_info">
                                <span>잡담양 : {{cat.tag_jobdam}}</span>
                                <span>필기양 : {{cat.tag_pilgi}}</span>
                                <span>진도 : {{cat.tag_jindo}}</span>
                            </p>
                        </div>
                    </div>

                    {% endfor %}
                </td>

                <td style="width:50%; text-align: center;">
                    {% for rev in review %}
                    <div id="review_box"
                    style="justify-content: center; display: inline-block; margin-bottom: 20px; margin: top 20px;">
                    <span id="date">{{rev.add_date}}에 작성한 후기</span>
                    <p>
    
                        <div id = "rev_title">강의명 : {{rev.lecture_title}}</div>
                        <div id = "rev_info">추천 등급 : {{rev.achivement}}</div>
                        <div id = "rev_info">잡담양 : {{rev.tag_jobdam}}</div>
                        <div id = "rev_info">진도 : {{rev.tag_jindo}}</div>
                        <div id = "rev_info">필기양 : {{rev.tag_pilgi}}</div>
                        <div id = "rev_info">코멘트 : {{rev.lec_comment}}</div>

                    </p>

                    </div>
                    {% endfor %}
                </td>
            </tr>
        </table>

    </div>

</body>

clients/templates/clients/recommendationpage.html
{% load static%}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/recommendationpage.css' %}">
</head>

<body>
    <div id="page1">
        <div id="header">
            <a href="{% url 'main' %}"><img id="logo" alt="My.Cl 로고" src="{% static 'img/로고.jpg' %}" /></a>
            <div id="recheader">강의 추천</div>
            <div id="auth" style="text-align: end;">
                {% if user.is_authenticated %}
                <a href="{% url 'logout' %}"><input type="button" id="authbutton" value="로그아웃"></a>
                <a href="{% url 'storage' user_id=user.id %}"><input type="button" id="authbutton"
                        value="{{ user.username }}님 마이페이지"></a>
                {% else %}
                <a href="{% url 'login' %}"><input type="button" id="authbutton" value="로그인"></a>
                <a href="{% url 'signup' %}"><input type="button" id="authbutton" value="회원가입"></a>
                {% endif %}
            </div>
        </div>

        <hr size="5px" color="pink">


        <table style="width: 100%; margin-top : 0px; margin-left:auto; margin-right: auto;">
            <tr style="vertical-align: top">
                <td style="width:50%; border-right:5px solid #fdb0b0; text-align: center;">
                    <div id="tag_box"
                        style="justify-content: center; display: inline-block; margin-bottom: 20px; margin: top 20px;">
                        <p>
                            <div id="tag_info">강의 사이트 : {{cho_tag.site}}</div>
                            <div id="tag_info">잡담양 : {{cho_tag.jobdam}}</div>
                            <div id="tag_info">필기양 : {{cho_tag.pilgi}}</div>
                            <div id="tag_info">진도 : {{cho_tag.jindo}}</div>
                        </p>
                    </div>

                </td>
                <td style="width:50%; text-align: center;">
                    {% for post in posts %}
                    <div id="box_model"
                        style="justify-content: center; display: inline-block; margin-bottom: 20px; margin: top 20px;">
                        <a href = "{{post.4}}" id="lec_title">{{ post.0 }}</p></a>
                        <p id="lec_info"> {{post.1}} 선생님 </p>
                    </div>

                    {% endfor %}


                </td>
            </tr>
        </table>



        {% if posts.has_previous %}
        <a href="?page=1" id="first">맨 처음 결과</a>
        <a href="?page={{posts.previous_page_number}}" id="prev">이전 결과</a>
        {% endif %}
        {% if posts.has_next %}
        <a href="?page={{posts.next_page_number}}" id="next">다음 결과</a>

        {% endif %}

    </div>
</body>

</html>

clients/templates/clients/registerpage.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/registerpage.css'%}">
</head>

<body>
    <div id="page1"> 
        <form action="{% url 'signup' %}" method="post" class="registerForm">
            {% csrf_token %}
            {% include "clients/form_errors.html" %}
            <a href="{% url 'main' %}"><img id="logo" alt="My.Cl 로고" src="{% static 'img/로고.jpg' %}"/></a>
            <div id="registertext">회원가입</div>
            <div class="idForm">
                <input type="text" class="id" name="username" id="username" placeholder="ID"
                    value="{{ form.username.value|default_if_none:'' }}">
            </div>
            <div class="passForm">
                <input type="password" class="pw" name="password1" id="password1" placeholder="PW"
                    value="{{ form.password1.value|default_if_none:'' }}">
            </div>
            <div class="passForm">
                <input type="password" class="pwcheck" name="password2" id="password2" placeholder="PW check"
                    value="{{ form.password2.value|default_if_none:'' }}">
            </div>
            <button type="submit" class="btn">
                회원가입
            </button>
            
        </form>
    </div>

</body>

clients/templates/clients/reviewpage.html
{% load static%}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/reviewpage.css' %}">
</head>

<body>
    <div id="page1">
        <div id="header">
            <a href="{% url 'main' %}"><img id="logo" alt="My.Cl 로고" src="{% static 'img/로고.jpg' %}" /></a>
            <div id="reviewheader">후기작성</div>
            <div id="auth" style="text-align: end;">
                {% if user.is_authenticated %}
                <a href="{% url 'logout' %}"><input type="button" id="authbutton" value="로그아웃"></a>
                <a href="{% url 'storage' user_id=user.id %}"><input type="button" id="authbutton"
                        value="{{ user.username }}님 마이페이지"></a>
                {% else %}
                <a href="{% url 'login' %}"><input type="button" id="authbutton" value="로그인"></a>
                <a href="{% url 'signup' %}"><input type="button" id="authbutton" value="회원가입"></a>
                {% endif %}
                <hr size="5px" color="pink">
            </div>
        </div>


        <div id="select_lecture">
            <div style="margin-bottom: 5px; font-size: 25px; font-weight: bolder;">수강한 강의를 입력하세요.</div>

            <form action="{% url 'review' %}" method='POST'> {% csrf_token %}
                <select name="site" id="id_site">
                    <option value="ebsi"> EBSi</option>
                    <option value="mega"> 메가스터디</option>
                    <option value="etoos"> 이투스</option>
                </select>
                <input type="text" name="search_key" value="{{ search_key }}" id="lecture_text">
                <span class="input-group-btn">
                    <input class="btn btn-default" type="submit" value="Search">
                </span>
                <hr size="3px" color="pink" width="400px">

            </form>

        </div>

        {% if post_lec%}
        <table style="margin-left: auto; margin-right: auto; margin-top: 20px">

            <thead style="font-weight: bold; font-size: x-large; font-family: '어그로'; border: 10px;">
                <th>강의명</th>
                <th>선생님</th>
                <th>과목</th>
                <th>학년</th>
            </thead>

            {% for post in post_lec %}
            <tr id="list_search">
                <td>{{post.title}}</td>
                <td>{{post.teacher}}</td>
                <td>{{post.subject}}</td>
                <td>{{post.grade}}</td>
                <td>
                    <form action="{% url 'for_review' %}" method='get'> {% csrf_token %}
                        <a href="{% url 'for_review' %}"><button name = "lecture_select" value="{{ post.title }}" id="submitbutton">후기
                                작성하기</button></a>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </table>
        {%endif%}





    </div>
</body>